//
//  FiniteAutomaton.h
//  Regularity
//
//  Created by Eric Bomgardner on 8/1/15.
//  Copyright (c) 2015 Eric Bomgardner. All rights reserved.
//

@import Foundation;

@class State;
@class Transition;

@interface FiniteAutomaton : NSObject

@property (nonatomic, copy, readonly) NSString *name;
@property (nonatomic, copy, readonly) NSArray *transitions;

/** Synthetic property generated by iterating through transitions and returning all states in the finite automaton. */
@property (nonatomic, copy, readonly) NSArray *states;

/** Designated initializer. */
- (instancetype)initWithName:(NSString *)name transitions:(NSArray *)transitions;

- (void)addTransition:(Transition *)transition;

@end
